server:
  port: 8002
spring:
  application:
    name: SHOPCAR-8002
  datasource:
    url: jdbc:mysql://localhost:3306/huawei
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 1800000
    host: 124.222.215.244
    port: 6379
    # redis密码
    password: cz1234
    lettuce:
      pool:
        # 最大连接数
        max-active: 30
        # 阻塞等待时间
        max-wait: 30
        # 最大空闲
        max-idle: 10
        # 最小空闲
        min-idle: 5



mybatis:
  configuration:
    # 开启数据库与java命名规范自动转换
    map-underscore-to-camel-case: true
    local-cache-scope: session  #一级缓存指定为session级别
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置自动设置别名的实体类的位置
  type-aliases-package: utils.entity
  # 设置mapper映射文件的位置
  mapper-locations: classpath:mappers/*.xml



# 修改暴露的端口  让自己的变化能被别人发现，好像是让自己的监控那个模块下面的请求可以被访问
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: localhost #eure服务端的实例名称
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # 表示自己端就是注册中心，我们就是用来维护服务的实例的，并不需要去检索服务
    fetch-registry: true
    # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      # 在客户端中这里写的是eureka server的地址，单机版的eureka中这里写的是他自己
      defaultZone: http://localhost:7001/eureka
