server:
  port: 80
spring:
  application:
    name: CUSTOMER-80

eureka:
  instance:
    hostname: localhost #eure服务端的实例名称
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # 表示自己端就是注册中心，我们就是用来维护服务的实例的，并不需要去检索服务
    fetch-registry: true
    # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      # 在客户端中这里写的是eureka server的地址，单机版的eureka中这里写的是他自己
      defaultZone: http://localhost:7001/eureka