server:
  port: 3344
spring:
  application:
    name: cloud-config-center-3344
  cloud:
    config:
      server:
        git:
          # git服务器上面的仓库的地址
          uri: https://github.com/CQYPIG/huawei_cloud_config.git
          # 搜索的目录
          search-paths:
            # 仓库的目录
            - huawei_cloud_config
          # 注意层级  跟搜索目录一个级别
          username: CQYPIG
          password: cz180864
      # 读取分支
      label: master